version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login-demo-app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      # H2データベース設定（インメモリモード）
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      # セキュリティ設定（開発環境用）
      - APP_SECURITY_PEPPER=${SECURITY_PEPPER:-defaultPepper123!}
      - APP_JWT_SECRET=${JWT_SECRET:-defaultJwtSecret456!}
      - APP_JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
    volumes:
      # ホットリロード用（開発時のみ）
      - ./build/libs:/app/libs:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge