name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build with Gradle
      run: ./gradlew bootJar
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: build/libs/*.jar

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: jar-artifact
        path: build/libs/
    
    # デプロイステップ（Railway tokenが設定されている場合のみ実行）
    - name: Check deployment readiness
      id: check-deploy
      run: |
        if [ -n "${{ secrets.RAILWAY_TOKEN }}" ]; then
          echo "deploy=true" >> $GITHUB_OUTPUT
        else
          echo "deploy=false" >> $GITHUB_OUTPUT
          echo "⚠️ RAILWAY_TOKEN is not set. Skipping deployment."
        fi
    
    - name: Deploy to Railway
      if: steps.check-deploy.outputs.deploy == 'true'
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        npm install -g @railway/cli
        railway up
    
    # 代替デプロイオプション（将来的な実装用）
    # - name: Deploy to AWS
    #   if: steps.check-deploy.outputs.deploy == 'false'
    #   run: echo "Alternative deployment methods can be configured here"